defaults:
  - hydra: default
  - env: default
  - log: default

worker: eval_linear_probe
output_dir: checkpoints/eval
job_name: eval_linear_probe_m_cashew_sr_model_lr_bilinear_resized_ep300_3
pretrain_job_name: # Set to the pretrain job name to load checkpoint from

# Dataset
dataset: m-cashew-plantation
data_path: /home/admin/AGML_ResearchGroup/geo_bench  # Path to geobench data directory
img_size: 224
num_classes: 7

# Geobench-specific parameters
partition: default  # Options: default, 1.00x_train, 0.50x_train, 0.20x_train
norm_operation: standardize  # Options: standardize, norm_yes_clip, norm_no_clip, satlas
band_names:  # Default: ["02 - Blue", "03 - Green", "04 - Red", "08 - NIR"]

# Model
encoder: vit_small
use_batchnorm: False

# Evaluation mode
eval_mode: linear_probe  # or 'finetune'

# Checkpoint
pretrained_checkpoint: /home/admin/john/LatentMIM/checkpoints/lr_model_with_bilinear_resizing/checkpoints/checkpoint_0300.pth # ${output_dir}/${pretrain_job_name}/checkpoints/checkpoint_latest.pth
resume: False

# Training
epochs: 100
warmup_epochs: 10
batch_size: 64
accum_iter: 1

# Optimizer
blr: # 1e-2
lr: 1e-3  # Will be computed from blr if not set
min_lr_frac: 1
weight_decay: 0.0
