defaults:
  - hydra: default
  - env: default
  - log: default

worker: eval_linear_probe
output_dir: checkpoints/eval
job_name: eval_linear_probe_mados_rapidai_sr_model_block_sampling_ep300_run4
pretrain_job_name: # Set to the pretrain job name to load from

# Dataset
dataset: mados
data_path: /home/admin/AGML_ResearchGroup/SuperResolution/mados
img_size: 224
filter_bands: [1, 2, 3, 6]  # BGR + NIR
num_classes: 15

# Model
encoder: vit_small
use_batchnorm: False

# Evaluation mode
eval_mode: linear_probe  # or 'finetune'

# Checkpoint
pretrained_checkpoint: /home/admin/john/LatentMIM/checkpoints/sr_model_rapidai_block_sampling/checkpoints/checkpoint_0300.pth
resume: False
checkpoint_metric: miou  # 'miou' or 'loss' - metric used to select best checkpoint for test

# Training
epochs: 100
warmup_epochs: 10
batch_size: 64
accum_iter: 1

# Optimizer
blr: # 1e-2
lr: 1e-3  # Will be computed from blr if not set
min_lr_frac: 1
weight_decay: 0.0