workers: 10

world_size: 1
rank: 0
dist_url: tcp://localhost:40012
dist_backend: nccl
port: 40012
node: localhost

distributed: True
seed:
gpu:
ngpu: 1
mem_gb: 62
pin_mem: True

slurm: False
slurm_suffix: ""
slurm_partition: abhinav,all
slurm_timeout: 360
nodelist: ""
exclude: ""
